@echo off
setlocal enabledelayedexpansion

REM Set working directory to where this batch file is located
cd /d "%~dp0"

if "%~1"=="" (
    echo ========================================================
    echo Error: No files provided.
    echo Usage: add_topic.bat ^<HTML_FILE_PATH_1^> [HTML_FILE_PATH_2...]
    echo Or simply drag and drop HTML files onto this batch file.
    echo ========================================================
    pause
    exit /b 1
)

echo Adding topic files...

REM Copy and rename
for %%F in (%*) do (
    set "filename=%%~nxF"
    set "filename=!filename: =_!"
    copy /Y "%%~F" "..\gas\data\!filename!" > nul
    echo Added: !filename!
)

REM Update data_index.gs
echo Updating gas/data_index.gs...
echo // This file is auto-generated by tools/add_topic.bat > "..\gas\data_index.gs"
echo const TOPICS_FILES = [ >> "..\gas\data_index.gs"
for %%F in (..\gas\data\*.html) do (
    set "name=%%~nF"
    echo   '!name!', >> "..\gas\data_index.gs"
)
echo ]; >> "..\gas\data_index.gs"

echo ========================================================
echo All files have been processed successfully!
echo Please re-deploy or clasp push to Google Apps Script.
echo ========================================================
pause
